## Data explorer for ACLED data
file renamed to `ACLED_data.csv` for simplification. Explorer uses folium for map import.

In [1]:
import pandas as pd
import folium
from narwhals import DataFrame

In [18]:
data = pd.read_csv("ACLED_data.csv")
#data = data[data["admin1"] == "North Indian Ocean"]
data

,week,region,country,admin1,event_type,sub_event_type,events,fatalities,population_exposure,disorder_type,centroid_latitude,centroid_longitude
0,2024-12-28,International Waters,Indian Ocean,North Indian Ocean,Strategic developments,Disrupted weapons use,1,0,0,Strategic developments,13.728,70.473
1,2024-12-28,Middle East,Yemen,Abyan,Battles,Government regains territory,3,0,"24,738",Political violence,13.627,46.228
2,2024-12-28,Middle East,Yemen,Abyan,Battles,Armed clash,3,0,"22,810",Political violence,13.627,46.228
3,2024-12-28,Middle East,Yemen,Ad Dali,Explosions/Remote violence,Shelling/artillery/missile attack,1,0,"4,845",Political violence,13.894,44.783
4,2024-12-28,Middle East,Yemen,Ad Dali,Battles,Armed clash,4,5,"15,460",Political violence,13.894,44.783
...,...,...,...,...,...,...,...,...,...,...,...,...
5479,2026-09-12,Middle East,Yemen,Taizz,Strategic developments,Other,3,0,0,Strategic developments,13.295,43.786
5480,2026-09-12,Middle East,Yemen,Taizz,Violence against civilians,Abduction/forced disappearance,1,0,0,Political violence,13.295,43.786
5481,2026-09-12,Middle East,Yemen,Taizz,Strategic developments,Disrupted weapons use,2,0,0,Strategic developments,13.295,43.786
5482,2026-09-12,Middle East,Yemen,Taizz,Strategic developments,Looting/property destruction,2,0,0,Strategic developments,13.295,43.786
5483,2026-09-12,Middle East,Yemen,Taizz,Protests,Peaceful protest,2,0,0,Demonstrations,13.295,43.786

In [49]:
unique_locations= data[['centroid_latitude', "centroid_longitude"]].drop_duplicates()

unique_locations

     centroid_latitude  centroid_longitude
0               13.728              70.473
1               13.627              46.228
3               13.894              44.783
6               12.806              44.788
8               14.326              45.216
11              14.779              43.218
13              16.596              45.599
15              17.057              51.824
16              15.308              43.499
17              15.420              44.192
19              16.116              43.941
20              14.540              44.306
21              16.529              48.627
22              16.094              43.204
23              14.088              44.175
25              13.320              44.762
27              15.333              45.452
29              14.657              43.687
30              17.088              44.042
32              15.393              44.475
33              14.651              46.620
34              13.295              43.786
235             12.508              53.893

In [15]:
avg_lat = data["centroid_latitude"].mean()
avg_long = data['centroid_longitude'].mean()
center =[avg_lat, avg_long]


# Create interactive map
m = folium.Map(location=center, zoom_start=5)
m

In [51]:
for i, v in unique_locations.iterrows():
    loc = [v["centroid_latitude"], v["centroid_longitude"]]
    folium.Marker(location=loc).add_to(m)

m