## Data explorer for ACLED data
file renamed to `ACLED_data_yemen.csv` and  `ACLED_data_mid_east.csv` for simplification. Explorer uses folium for map import.

In [1]:
import pandas as pd
import folium
from narwhals import DataFrame

In [2]:
data = pd.read_csv("ACLED_data_mid_east.csv")
#data = data[data["admin1"] == "North Indian Ocean"]
data

,week,region,country,admin1,event_type,sub_event_type,events,fatalities,population_exposure,disorder_type,centroid_latitude,centroid_longitude
0,2025-09-27,International Waters,Indian Ocean,North Indian Ocean,Protests,Peaceful protest,2,0,0,Demonstrations,13.728,70.473
1,2025-09-27,International Waters,Indian Ocean,North Indian Ocean,Explosions/Remote violence,Shelling/artillery/missile attack,1,1,0,Political violence,13.728,70.473
2,2025-09-27,International Waters,Indian Ocean,North Indian Ocean,Explosions/Remote violence,Air/drone strike,1,0,0,Political violence,13.728,70.473
3,2025-09-27,Middle East,Iran,Bushehr,Protests,Peaceful protest,8,0,"24,725",Demonstrations,28.785,51.504
4,2025-09-27,Middle East,Iran,East Azerbaijan,Protests,Peaceful protest,3,0,"14,390",Demonstrations,38.086,46.692
...,...,...,...,...,...,...,...,...,...,...,...,...
5594,2026-09-19,Middle East,Yemen,Taizz,Strategic developments,Change to group/activity,7,0,0,Strategic developments,13.295,43.786
5595,2026-09-19,Middle East,Yemen,Taizz,Strategic developments,Disrupted weapons use,5,0,0,Strategic developments,13.295,43.786
5596,2026-09-19,Middle East,Yemen,Taizz,Violence against civilians,Abduction/forced disappearance,1,0,"15,009",Political violence,13.295,43.786
5597,2026-09-19,Middle East,Yemen,Taizz,Strategic developments,Looting/property destruction,2,0,0,Strategic developments,13.295,43.786
5598,2026-09-19,Middle East,Yemen,Taizz,Explosions/Remote violence,Remote explosive/landmine/IED,1,0,"1,011",Political violence,13.295,43.786

In [10]:
unique_locations= data[['centroid_latitude', "centroid_longitude", 'country', 'event_type']].drop_duplicates()
unique_locations

,centroid_latitude,centroid_longitude,country,event_type
0,13.728,70.473,Indian Ocean,Protests
1,13.728,70.473,Indian Ocean,Explosions/Remote violence
3,28.785,51.504,Iran,Protests
4,38.086,46.692,Iran,Protests
5,38.086,46.692,Iran,Strategic developments
...,...,...,...,...
3866,13.320,44.762,Yemen,Riots
4160,37.298,54.880,Iran,Explosions/Remote violence
4289,20.476,56.904,Oman,Strategic developments
4894,13.894,44.783,Yemen,Riots
4938,14.657,43.687,Yemen,Strategic developments

In [3]:
data['country'].value_counts()

country
Yemen                   3103
Iran                    2278
Indian Ocean             113
United Arab Emirates      68
Oman                      37
Name: count, dtype: int64

In [11]:
avg_lat = data["centroid_latitude"].mean()
avg_long = data['centroid_longitude'].mean()
center =[avg_lat, avg_long]


# Create interactive map
m = folium.Map(location=center, zoom_start=5)

In [14]:
for i, v in unique_locations.iterrows():
    loc = [v["centroid_latitude"], v["centroid_longitude"]]
    folium.Marker(location=loc,
                  popup=v[['country', 'event_type']]
                  ).add_to(m)

m

## Port / Shipping Data Explorer

In [7]:
# data import
chokepoints_data = pd.read_csv('Daily_Chokepoints_Data.csv')
chokepoints_data

,date,year,month,day,portid,portname,n_container,n_dry_bulk,n_general_cargo,n_roro,...,n_cargo,n_total,capacity_container,capacity_dry_bulk,capacity_general_cargo,capacity_roro,capacity_tanker,capacity_cargo,capacity,ObjectId
0,2019/01/01,2019,1,1,chokepoint1,Suez Canal,15,15,9,4,...,43,61,1018466,618654,112660,21900,1279775,1771682,3051458,1
1,2019/01/02,2019,1,2,chokepoint1,Suez Canal,24,4,6,6,...,40,50,1534924,227315,8536,37934,518306,1808711,2327017,2
2,2019/01/03,2019,1,3,chokepoint1,Suez Canal,13,14,9,2,...,38,62,555097,977689,39398,10829,868092,1583014,2451107,3
3,2019/01/04,2019,1,4,chokepoint1,Suez Canal,17,11,2,2,...,32,47,1044184,430139,3673,3430,836954,1481428,2318382,4
4,2019/01/05,2019,1,5,chokepoint1,Suez Canal,19,9,1,1,...,30,43,1215509,777548,4587,5567,628481,2003212,2631693,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79151,2025/02/22,2025,2,22,chokepoint28,Kerch Strait,0,0,3,0,...,3,3,0,0,1982,0,0,1982,1982,79152
79152,2025/02/23,2025,2,23,chokepoint28,Kerch Strait,0,4,5,0,...,9,16,0,114844,1057,0,4440,115901,120341,79153
79153,2025/02/24,2025,2,24,chokepoint28,Kerch Strait,0,2,4,0,...,6,9,0,0,1933,0,96486,1933,98420,79154
79154,2025/02/25,2025,2,25,chokepoint28,Kerch Strait,0,3,8,0,...,11,13,0,0,11431,0,2166,11431,13597,79155
79155,2025/02/26,2025,2,26,chokepoint28,Kerch Strait,0,2,5,0,...,7,13,0,28607,4619,0,191854,33227,225081,79156

In [8]:
chokepoints_data['portname'].value_counts()

portname
Suez Canal              2827
Panama Canal            2827
Bosporus Strait         2827
Bab el-Mandeb Strait    2827
Malacca Strait          2827
Strait of Hormuz        2827
Cape of Good Hope       2827
Gibraltar Strait        2827
Dover Strait            2827
Oresund Strait          2827
Taiwan Strait           2827
Korea Strait            2827
Tsugaru Strait          2827
Luzon Strait            2827
Lombok Strait           2827
Ombai Strait            2827
Bohai Strait            2827
Torres Strait           2827
Sunda Strait            2827
Makassar Strait         2827
Magellan Strait         2827
Yucatan Channel         2827
Windward Passage        2827
Mona Passage            2827
Balabac Strait          2827
Bering Strait           2827
Mindoro Strait          2827
Kerch Strait            2827
Name: count, dtype: int64